In [1]:
import numpy as np

Problem Statement 1: 
Write a function so that the columns of the output matrix are powers of the input vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 

HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde.


In [17]:
def Vandermondematrix(arr,n=0,increasing=False):
    '''
    three arguments 
    arr=pass an array of a 1d vector
    n=no of columns by default n=length of array
    increaing (bool type) if True the column order will be in increasing order
    by default increasing =False so the column order will be in decreasing
    '''
    if n==0:
        n=len(arr)
    if not increasing:
        list1=[[arr**(n-i-1)] for i in range(n)]
        return print(np.mat(np.array(list1).transpose()))
    else:
        list1=[[arr**(n-i-1)] for i in range(n)]
        list1.reverse()
        return print(np.mat(np.array(list1).transpose()))

In [11]:
Vandermondematrix(np.array([1,2,3,4]))

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [16]:
Vandermondematrix(np.array([1,2,3,4]),n=6)#for different n

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]]


In [15]:
Vandermondematrix(np.array([1,2,3,4]),increasing=True)#giving increasing =True

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


Problem Statement 2: 

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of  the given sequence is
defined as follows: 

The moving average sequence has n-k+1 elements as shown below. 

The moving averages with k=4 of a ten-value sequence (n=10) is shown below 

i 1 2 3 4 5 6 7 8 9 10 

===== == == == == == == == == == == 

Input 10 20 30 40 50 60 70 80 90 100  

y1 25 = (10+20+30+40)/4 

y2 35 = (20+30+40+50)/4 

y3 45 = (30+40+50+60)/4 

y4 55 = (40+50+60+70)/4 

y5 65 = (50+60+70+80)/4 

y6 75 = (60+70+80+90)/4 

y7 85 = (70+80+90+100)/4 

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window: 

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. 


In [18]:
def movingaverage(n,k):
    arr=np.array([])
    for i in range(len(n)-k+1):
        arr=np.append(arr,(round(sum(n[i:(i+k)])/k,2)))
        
    print(list(arr))       

In [19]:
movingaverage([10,20,30,40,50,60,70,80,90,100],4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]


In [20]:
movingaverage( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
